### ISSUE TITLE
Bad file in list of requirements

### ISSUE THREAD

**Issue by martinstreicher** [whazzmaster/fitgem#41]
It looks like the file `fitgem/locales` no longer exists, but it remains a requirement in `client.rb.` This causes failures.

**Comment by whazzmaster** [comment]
Going to fix this as soon as I get home this evening, and I'll push a new gem. Please force gem install at v0.11.0 until new gem is cut.

**Comment by whazzmaster** [comment]
Closed by db21e6dbf2d74786843ce68fb22b4fd843952e26
