### ISSUE TITLE
Upgrade for OAuth 2.0

### ISSUE THREAD

**Issue by gedankenstuecke** [whazzmaster/fitgem#48]
Just to bump the issue already raised with #44 and the switch isn't too far in the future. Is there any recommendation on which alternative Gem to use?

**Comment by gupta-ankit** [comment]
@gedankenstuecke I have written an OAuth2 version for fitgem ([fitgem_oauth2](https://github.com/gupta-ankit/fitgem_oauth2)), if you would like to give it a shot.

**Comment by gedankenstuecke** [comment]
Thanks so much, will have a look at it @gupta-ankit :smile:
